name: Deploy to production

on:
  push:
    branches: [deploy-frontend]
    paths:
      - ".github/workflows/chat-deploy.yml"
      - "back-end/services/chatService/**/*"

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: ${{ secrets.CHAT_REPO }}
  IMAGE_TAG: latest
  AWS_DEFAULT_OUTPUT: json

jobs:
  build-and-push:
    name: Push Chats Service to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag the image
        working-directory: ./back-end/services/chatService
        run:
          # Build and tag the image
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .
      - name: Push the image into ECR
        id: push-image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Download task definition
        run: aws ecs describe-task-definition --task-definition ecs-fargate-cs3219-chatservice --query taskDefinition --region ap-southeast-1 > task-definition.json

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@master
        with:
          task-definition: task-definition.json
          service: chat-public
          cluster: ecs-fargate-cluster-cs3219
          wait-for-service-stability: true
          force-new-deployment: true
