on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/front_end-test.yml'
      - 'front-end/**/*'

name: Frontend Cypress Tests

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        working-directory: ./front-end
        run: npm install
      - name: Testing
        working-directory: ./front-end
        run: npx cypress run
