name: Deploy to production

on:
  push:
    branches: [ deploy-frontend ]
    paths:
      - '.github/workflows/front-end-deploy.yml'
      - 'front-end/**/*'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}

jobs:
  build-and-push:
    name: Push Front-end to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
          aws-region: ap-southeast-1

      - name: Installing dependencies
        working-directory: ./front-end
        run: npm i
      
      - name: Build
        working-directory: ./front-end
        run: npm run build
        
      - name: Deploy
        working-directory: ./front-end
        run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET }}
      
      - name: Push changes to CloudFront
        working-directory: ./front-end
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION }} --paths "/*" --no-cli-pager
      
